/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Listly API v4
 * OpenAPI spec version: 1.0.0
 */

export type FindImagesParams = {
  q: string;
  page?: number;
  per_page?: number;
};
