/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Listly API v4
 * OpenAPI spec version: 1.0.0
 */
import type {Meta} from './meta';
import type {Image} from './image';

export interface ImageCollection {
  meta: Meta;
  results: Image[];
}
