/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Listly API v4
 * OpenAPI spec version: 1.0.0
 */

export interface Image {
  name?: string;
  description?: string;
  image?: string;
  preview_image?: string;
  tags?: string[];
  url?: string;
  media_type?: string;
  media_source?: string;
  media_id?: number;
}
