/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Listly API v4
 * OpenAPI spec version: 1.0.0
 */

export interface Meta {
  count: number;
  q: string;
  totalCount: number;
  type: string;
}
